server {
    listen 80;

    # Configuration essentielle pour les SPA (Angular/Ionic)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # (Autres configurations de cache ou de log...)
}