server {
    listen 80;
    
    # 💡 CORRECTION : Spécifier le chemin racine de vos fichiers
    root /usr/share/nginx/html; 
    index index.html; # Optionnel, mais bonne pratique

    # Configuration essentielle pour les SPA (Angular/Ionic)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # (Autres configurations de cache ou de log...)
}